# EpicWarning configuration file.


# Messages for plugin
messages:
  console messages:
    you can not use that in console: ''
  warn:
    no permission: ''
    too many args: ''
    usage: ''    
# Warning GUI
gui:
  first row:
    displaynames:
        one: 'test'
        two: 'test2'
        three: 'test3'
  third row:
    displaynames:
        one: 'one'
        two: 'two'
        three: 'three'
        four: 'four'
        five: 'five'
  fourth row:
    displaynames:
        one: 'one'
        two: 'two'
        three: 'three'
        four: 'four'
        five: 'five'     
# Warning Options (For in the gui.)
warning options:
  options:
    one: 'ADD'
    two: 'ADD'
    three: 'ADD2'
    four: 'KICK'
    five: 'BAN'
    six: 'TEMPBAN2'
    seven: 'TEMPBAN5'
    eight: 'ADD10'
    nine: 'ADD50'