name: EpicWarning
main: me.justbru00.epic.warning.Main.EpicWarning
version: 1.0
description: Warns players of wrong actions.
author: Justin Brubaker

commands:
 warn:
       description: Warns players of wrong actions. 
    